[workspace]
resolver = "3"
members = ["engine-core", "gateway", "protocol", "runtime"]

[workspace.dependencies]
once_cell = "1.21.3"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
crossbeam-channel = "0.5.15"
